services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: bot
    volumes:
      - ./settings.json:/app/settings.json
    command: ["/app/bot"]

